version: "3"
services:
  api:
    image: gdc-api
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ${APP_NAME}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - /app/node_modules
      - ${PWD}:/app
    command: ${APP_CMD}

networks:
  default:
    external:
      name: ${APP_NETWORK}
